apiVersion: v1
kind: Secret
metadata:
  name: prediction-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prediction-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Default: "postgres" base64 encoded. CHANGE IN PRODUCTION using --set or external secret
  POSTGRES_PASSWORD: {{ "postgres" | b64enc | quote }}
  DB_PASSWORD: {{ "postgres" | b64enc | quote }}
